name: explain
env:
  LOG_LEVEL: INFO
on:
  schedule:
    - cron:  '0 9 * * *' # Everyday 1h after predictions
  workflow_dispatch: # Allow for manual trigger from github.com
jobs:
  explain-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Moscow
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Moscow
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Download model input from artifact
        uses: aochmann/actions-download-artifact@master
        with:
          name: model_input.csv
          latest: true
          path: ./data/
      - name: Download predictions from artifact
        uses: aochmann/actions-download-artifact@master
        with:
          name: predictions-2024.csv
          latest: true
          path: ./data/
      - name: Download model from artifact
        uses: aochmann/actions-download-artifact@master
        with:
          name: model.joblib
          latest: true
          path: ./data/
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to explain predictions
        run: |
          pipenv run python . explain
      - name: Upload SHAP values dataset as artifact
        uses: actions/upload-artifact@v2
        with:
          name: shap_values-2024.csv
          path: ./data/shap_values-2024.csv
          retention-days: 10
