name: predict
on:
  workflow_dispatch: # Allow for manual trigger from github.com
jobs:
  make-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Moscow
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Moscow
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upload predictions as artifact
        uses: actions/upload-artifact@v2
        with:
          name: predictions.csv
          path: ./data/initial_dates/predictions.csv
          retention-days: 1
      - name: Upload history as artifact
        uses: actions/upload-artifact@v2
        with:
          name: history.csv
          path: ./data/initial_dates/history.csv
          retention-days: 1