[global]
disableWatchdogWarning = true
sharingMode = "off"
developmentMode = false

[server]
headless = true
enableCORS=true
enableXsrfProtection=true

[theme]
primaryColor =  "#F7630C"
textColor="#EFECEC" 
backgroundColor = "#525050"
secondaryBackgroundColor="#2E2D2D"